Algoritmo "contagemSaltoContador"

Var

valor, salto, contador: Inteiro

Inicio

contador <- 0
     Escreva("Quer contar ate quanto? ")
     Leia(valor)
     Escreva("Qual sera o valor do salto? ")
     Leia(salto)
     Enquanto (contador <= valor) faca
         Escreval (contador)
         contador <- contador + salto
     FimEnquanto
     Escreval ("Terminei de contar!")

Fimalgoritmo